-
  name: custom_1
  inputs:
    - question
    - reference_answer
    - actual_answer
    - reference_steps
    - actual_steps
  steps_name: retrieval
  steps_keys:
    - output
  instructions: |
    Given the question, evaluate the actual answer based on the
    reference answer.
    
    Also evaluate the actual context based on the reference context.
    
    Also evaluate the actual steps based on the reference steps.
  outputs:
    custom_1_answer_score: fraction between 0 and 1
    custom_1_answer_reason: reason for your evaluation of the answer
    custom_1_steps_score: fraction between 0 and 1
    custom_1_steps_reason: reason for your evaluation of the steps
